parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\PostController:
        arguments:
            $postsDirectory: '%kernel.project_dir%/public/uploads/posts'
        tags: ['controller.service_arguments']

    App\Service\AiTaskGeneratorService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\Service\AiMessengerService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'