parameters:
    app.env_empty_string: ''
    google_client_id: '%env(default:app.env_empty_string:GOOGLE_CLIENT_ID)%'
    google_client_secret: '%env(default:app.env_empty_string:GOOGLE_CLIENT_SECRET)%'
    twilio.accountSid: '%env(default:app.env_empty_string:TWILIO_ACCOUNT_SID)%'
    twilio.authToken: '%env(default:app.env_empty_string:TWILIO_AUTH_TOKEN)%'
    twilio.fromNumber: '%env(default:app.env_empty_string:TWILIO_FROM_NUMBER)%'
    twilio.toNumber: '%env(default:app.env_empty_string:TWILIO_TO_NUMBER)%'
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\AiTaskGeneratorService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\Service\AiMessengerService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\Service\GeminiService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\Service\GroqService:
        arguments:
            $groqApiKey: '%env(GROQ_API_KEY)%'

    App\Service\SpotifySuggestionService:
        arguments:
            $spotifyClientId: ''
            $spotifyClientSecret: ''

    App\Service\TwilioSmsService:
        arguments:
            $accountSid: '%twilio.accountSid%'
            $authToken: '%twilio.authToken%'
            $fromNumber: '%twilio.fromNumber%'
            $toNumber: '%twilio.toNumber%'
            $connection: '@doctrine.dbal.default_connection'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%uploads_directory%'

